# Generated by Django 3.2.7 on 2021-09-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='author',
        ),
    ]
